### ISSUE TITLE
Not allowed to load local resource

### ISSUE THREAD

**Issue by CtacikKarasik** [chinfeng/ch-app#2] opened 2021-03-11 12:08 UTC
Hello
After launching, I see errors. What could be wrong? 
Win 64 OS
![image (1)](https://user-images.githubusercontent.com/55653815/110784932-56931480-827b-11eb-8331-337ba2ca8e2c.png)
![image (2)](https://user-images.githubusercontent.com/55653815/110785069-8f32ee00-827b-11eb-8f73-8f07bc48b8d2.png)

**Comment by chinfeng** [comment] 2021-03-11 12:27
Agora-electron-sdk has 32bit built-in binary executable. Try to use 32bit node to run or package the project.

**Comment by CtacikKarasik** [comment] 2021-03-11 12:31
how to do it correctly?

**Comment by chinfeng** [comment] 2021-03-11 12:36
I just using 32bit node environment. Or you can try to remove "node_modules" directory and run `yarn --arch=ia32` to reinstall 32bit deps.

**Comment by Xutan1337** [comment] 2021-03-12 03:52
> I just using 32bit node environment. Or you can try to remove "node_modules" directory and run `yarn --arch=ia32` to reinstall 32bit deps.

i have tried this solution and the issue is still persistent. any other idea?

**Comment by CtacikKarasik** [comment] 2021-03-12 08:52
I am using a 32 bit host environment and it worked. Thank!

**Comment by chinfeng** [comment] 2021-03-12 10:04
> > I just using 32bit node environment. Or you can try to remove "node_modules" directory and run `yarn --arch=ia32` to reinstall 32bit deps.
> 
> i have tried this solution and the issue is still persistent. any other idea? this is what i've done : https://pastebin.com/sbdLpqLS

Maybe --arch=ia32 not working under 64bit environment. Try 32bit node environment. 

Maybe agora-electron-sdk only works under 32bit node. I am closing this issue.

**Closed by chinfeng** 2021-03-12 10:04 UTC
